<a href="https://colab.research.google.com/github/CarolinaOliveira001/Complex_Network/blob/main/Exercise_1_Twitter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install snap-stanford

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 11.6 MB 5.2 MB/s 


In [ ]:
#TWITTER

In [ ]:
#Here are the imports for the whole code.

In [3]:
import snap
import numpy as np

In [ ]:
#We create a directed graph.

In [4]:
graph = snap.TNGraph.New()

In [ ]:
#Here is the file of dataset we are using.

In [7]:
filename = "/content/twitter/1046661.edges"

In [ ]:
#We read through the dataset file line by line. At each line we split it and we get two integers. Then we check if 
#both integers are id of some nodes in the graph. If not, then the one(s) which are not already id of some nodes, 
#they are added as such. At the end, we add an edges between the two nodes.

In [8]:
with open(filename) as f:
    for line in f:
        x = line.split()
        a = int(x[0])
        b = int(x[1])
        
        if graph.IsNode(a) != True:
            graph.AddNode(a)
        if graph.IsNode(b) != True:
            graph.AddNode(b)
            
        graph.AddEdge(a, b)

In [ ]:
#Question (a)

In [ ]:
#First we create a variable and put it to 0. It goes through the nodes and counts them. 
#We do a similar code for the edges.

In [9]:
numberOfNodes = 0
for i in graph.Nodes():
    numberOfNodes = numberOfNodes + 1
print("In the graph, there are", numberOfNodes, "nodes.")

In the graph, there are 128 nodes.


In [10]:
numberOfEdges = 0
for i in graph.Edges():
    numberOfEdges = numberOfEdges + 1
print("In the graph, there are", numberOfEdges, "edges.")

In the graph, there are 1642 edges.


In [ ]:
#Question (b)

In [ ]:
#We create two lists, one in-degree and one out-degree. We go through the nodes and we append their degree to the 
#corresponding empty list.

In [12]:
listOfInDegrees = []
listOfOutDegrees = []

for i in graph.Nodes():
    listOfInDegrees.append(i.GetInDeg())
    listOfOutDegrees.append(i.GetOutDeg())
    
print("Here is a list of the in-degrees of the nodes in the graph:\n", listOfInDegrees)
print("Here is a list of the out-degrees of the nodes in the graph:\n", listOfOutDegrees)

Here is a list of the in-degrees of the nodes in the graph:
 [32, 8, 41, 3, 10, 21, 10, 32, 15, 19, 15, 40, 10, 36, 68, 3, 54, 7, 42, 38, 16, 12, 48, 47, 18, 40, 19, 29, 9, 44, 31, 44, 4, 34, 3, 45, 30, 9, 36, 13, 6, 28, 21, 40, 1, 6, 8, 15, 14, 45, 1, 7, 3, 11, 26, 17, 11, 22, 2, 18, 1, 34, 5, 9, 5, 3, 9, 2, 2, 29, 17, 2, 9, 2, 16, 9, 1, 7, 1, 5, 4, 3, 7, 1, 5, 7, 1, 1, 1, 1, 9, 4, 5, 1, 4, 4, 3, 6, 0, 3, 8, 5, 2, 1, 9, 1, 1, 4, 2, 1, 2, 2, 9, 1, 4, 1, 3, 5, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0]
Here is a list of the out-degrees of the nodes in the graph:
 [32, 0, 36, 3, 11, 31, 9, 42, 30, 30, 32, 52, 10, 22, 63, 5, 47, 7, 36, 20, 21, 33, 42, 39, 21, 48, 32, 39, 7, 30, 33, 35, 2, 16, 3, 30, 26, 24, 50, 27, 15, 34, 20, 0, 2, 0, 9, 27, 2, 34, 1, 9, 4, 0, 27, 14, 11, 29, 3, 0, 5, 27, 0, 14, 7, 2, 8, 3, 3, 20, 50, 5, 11, 2, 18, 7, 0, 7, 1, 0, 9, 4, 7, 2, 7, 10, 2, 1, 1, 2, 13, 5, 2, 1, 4, 4, 1, 12, 2, 0, 0, 2, 3, 1, 9, 1, 1, 4, 1, 1, 6, 3, 0, 1, 0, 0, 3, 1, 1, 1, 2, 2, 0, 0, 1, 1, 0, 1]


In [ ]:
#Now let us look at the maximum in-degree of the nodes. We go through the list of the nodes' in-degree and we update 
#the value of the maximum in-degree if the in-degree from the list is bigger than the maximum in-degree.
#For the average in-degree, we go through the list of in-degrees and add each value in it together. At the end, we 
#calculate the sum of the in-degrees divided by the total number of nodes.

In [13]:
maximumInDegree = 0
averageInDegree = 0

for i in listOfInDegrees:
    averageInDegree = averageInDegree + i
    
    if maximumInDegree < i:
        maximumInDegree = i

averageInDegree = averageInDegree / numberOfNodes

print("Maximum in-degree is:", maximumInDegree)
print("Average in-degree is:", averageInDegree)

Maximum in-degree is: 68
Average in-degree is: 12.828125


In [ ]:
#We calculate the same for out-degrees of the nodes.

In [14]:
maximumOutDegree = 0
averageOutDegree = 0

for i in listOfOutDegrees:
    averageOutDegree = averageOutDegree + i
    
    if maximumOutDegree < i:
        maximumOutDegree = i

averageOutDegree = averageOutDegree / numberOfNodes

print("Maximum out-degree is:", maximumOutDegree)
print("Average out-degree is:", averageOutDegree)

Maximum out-degree is: 63
Average out-degree is: 12.828125


In [ ]:
#Small remake is that the average in-degree equals the average of out-degree as expected. However the maximum 
#in-degree can be different from the maximum out-degree. In our case, the maximum in-degree is bigger than the 
#maximum out-degree.

In [ ]:
#Question (c)

In [ ]:
#We initialize a directed graph, called graphPartial.

In [15]:
graphPartial = snap.TNGraph.New()

In [ ]:
#We create a list and define the number of partial nodes as being 6. While the list does not contain 5 nodes, random 
#picked nodes from the previous graph are added to the list if they are not already inside. The last for-loop adds 
#each node from the list of partial nodes to the partial graph.

In [16]:
listOfPartialNodes = []
numberOfPartialNodes = 5

while len(listOfPartialNodes) < numberOfPartialNodes:
    NId = graph.GetRndNId()
    if NId not in listOfPartialNodes:
        listOfPartialNodes.append(NId)

for node in listOfPartialNodes:
    graphPartial.AddNode(node)
print("The nodes chosen are", listOfPartialNodes)

The nodes chosen are [6752812, 1159201, 820485, 6194262, 9921142]


In [ ]:
#We go through the dataset file and add an edge to the partial graph for every two nodes which were written in the 
#same line (separated by a whitespace) on the file.

In [17]:
with open(filename) as f:
    for line in f:
        x = line.split()
        a = int(x[0])
        b = int(x[1])
        
        if a in listOfPartialNodes and b in listOfPartialNodes:
            graphPartial.AddEdge(a, b)

In [ ]:
#As we done it before, we count the number of nodes in the partial graph.

In [18]:
numberOfPartialNodes = 0
for i in graphPartial.Nodes():
    numberOfPartialNodes = numberOfPartialNodes + 1
print("There are", numberOfPartialNodes, "nodes in the partial graph.")

There are 5 nodes in the partial graph.


In [ ]:
#As we done it before, we count the number of edges in the partial graph.

In [19]:
numberOfPartialEdges = 0
for i in graphPartial.Edges():
    numberOfPartialEdges = numberOfPartialEdges + 1
print("There are", numberOfPartialEdges, "edges in the partial graph.")

There are 2 edges in the partial graph.


In [ ]:
#We create a 5x5 matrix with 0 at every entry. The number 5 is the number of node for the partial graph, it will 
#change when desired the number of nodes changes. Then at every entry, it checks if there is an edge between every 
#two nodes. If there is an edge, then at that entry there will be a 1. It checks by trying to add an edge between the
#two nodes. If it is successful, we put at that entry a 0 and deletes the added edge. Otherwise, it will be a 1.  

In [20]:
adjMatrix = np.empty((numberOfPartialNodes,numberOfPartialNodes))

row = 0
for i in listOfPartialNodes:
    column = 0
    
    for j in listOfPartialNodes:
        if graphPartial.AddEdge(i, j) == -1:
            adjMatrix[row][column] = 0
            graphPartial.DelEdge(i, j)
        else:
            adjMatrix[row][column] = 1
        
        column = column + 1
    row = row + 1

print("The adjacency matrix of the partial graph with the following nodes", listOfPartialNodes, "is:\n", adjMatrix)

The adjacency matrix of the partial graph with the following nodes [6752812, 1159201, 820485, 6194262, 9921142] is:
 [[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [ ]:
#Small notice: since i am picking nodes at random, there can be some nodes which have no edge in between them. This
#leads to a zero adjacency matrix.

In [ ]:
#The adjacency matrix tells a lot about a graph. First, we can see if the matrix is symmetric or asymmetric.
#If it is asymmetric, we know that the graph is a directed graph. However, if it symmetric, we know that the graph is
#undirected graph.
#Now the entries tell us if there is an edge between the node at i column and the node at j row. The number 1 at the
#entry means there is an edge between the two nodes. The number 0 at the entry means there is an edge between the two
#nodes. So with only the adjacency matrix, we should be able to reconstruct the graph (or an equivalent one). 

#Exercise sheet 2

In [ ]:
#Here are the other dataset files. However for this assignment, we haven't done anything with it.

In [ ]:
f = open("/Users/carolina/Documents/Semester_9/Analysis_of_Complex_Network/Group4/Twitter-Ego/1046661.circles", "r")
print(f.read())

0	1269251
1	1468951	678953	1118781	2217251
2	9921142
3	18498684
4	8295072
5	1117341	1403031	1118161
6	51421542



In [ ]:
f = open("/Users/carolina/Documents/Semester_9/Analysis_of_Complex_Network/Group4/Twitter-Ego/1046661.egofeat", "r")
print(f.read())

0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0



In [ ]:
f = open("/Users/carolina/Documents/Semester_9/Analysis_of_Complex_Network/Group4/Twitter-Ego/1046661.feat", "r")
print(f.read())

3527151 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
6089552 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
8639402 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [ ]:
f = open("/Users/carolina/Documents/Semester_9/Analysis_of_Complex_Network/Group4/Twitter-Ego/1046661.featnames", "r")
print(f.read())

0 #...
1 #1
2 #1:
3 #4sqDay
4 #Blacklist
5 #CISPA
6 #Caps
7 #CapsBruins
8 #Discovery
9 #Eureka
10 #FF
11 #GamesWithFriends
12 #KONY2012
13 #OWS
14 #Occupy
15 #OccupyWallStreet
16 #SOPA.
17 #SXSW
18 #Science
19 #Storify
20 #TED
21 #TakeWallStreet
22 #Volunteer
23 #WTF
24 #bieber
25 #blogger
26 #caps
27 #censorship
28 #climate
29 #coffee
30 #eco
31 #edX
32 #energy
33 #fail
34 #fb
35 #ff
36 #fish
37 #fracking
38 #green
39 #health
40 #iTunes
41 #impressive
42 #jobs
43 #lastfm
44 #love
45 #news
46 #np
47 #occupywallstreet
48 #occupywallstreet,
49 #opendata
50 #p2
51 #photography
52 #random
53 #science
54 #signon
55 #takewallstreet
56 #tcot
57 #tech
58 #truth
59 @AddThis
60 @AnnOhio
61 @BadAstronomer:
62 @Bayer_sd
63 @BlondeByDesign
64 @CNN
65 @City
66 @DalaiLama
67 @Dropbox.
68 @EcoInteractive:
69 @FastCoExist
70 @GetGlue
71 @GetGlue!
72 @GuyKawasaki:
73 @HuffingtonPost
74 @HuffingtonPost:
75 @KeithOlbermann:
76 @KurzweilAINews:
77 @LOLGOP:
78 @LRO_NASA
79 @Lake
80 @LanceUlanoff:
81 @MsAmbe