<a href="https://colab.research.google.com/github/CarolinaOliveira001/Complex_Network/blob/main/Exercise_1_Facebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#FACEBOOK

In [ ]:
#Here are the imports for the whole code.

In [12]:
import snap
import numpy as np

In [13]:
from google.colab import files

In [ ]:
#We create an undirected graph.

In [4]:
graph = snap.TUNGraph.New()

In [ ]:
#Here is the file of dataset we are using.

In [14]:
filename = "/Users/carolina/Documents/Semester_9/Analysis_of_Complex_Network/Group4/Facebook-Ego/414.edges"

FileNotFoundError: ignored

In [ ]:
#We read through the dataset file line by line. At each line we split it and we get two integers. 
#Then we check if both integers are id of some nodes in the graph. If not, then the one(s) 
#which are not already id of some nodes, they are added as such. At the end, we add an edges between the two nodes.

In [10]:
with open(filename) as f:
    for line in f:
        x = line.split()
        a = int(x[0])
        b = int(x[1])
        
        if graph.IsNode(a) != True:
            graph.AddNode(a)
        if graph.IsNode(b) != True:
            graph.AddNode(b)
            
        graph.AddEdge(a, b)

FileNotFoundError: ignored

In [15]:
labels = {}
for NI in graph.Nodes():
        labels[NI.GetId()] = str(NI.GetId())
graph.DrawGViz(snap.gvlDot, "output.png", " ", labels)

In [ ]:
#Question (a)

In [ ]:
#First we create a variable and put it to 0. It goes through the nodes and counts them. 
#We do a similar code for the edges.

In [ ]:
numberOfNodes = 0
for i in graph.Nodes():
    numberOfNodes = numberOfNodes + 1
print("In the graph, there are", numberOfNodes, "nodes.")

In the graph, there are 150 nodes.


In [ ]:
numberOfEdges = 0
for i in graph.Edges():
    numberOfEdges = numberOfEdges + 1
print("In the graph, there are", numberOfEdges, "edges.")

In the graph, there are 1693 edges.


In [ ]:
#Question (b)

In [ ]:
#We create an empty list. We go through the nodes and we append their degree in the previously empty list.

In [ ]:
listOfDegrees = []

for i in graph.Nodes():
    listOfDegrees.append(i.GetDeg())
    
print("Here is a list of the degrees of the nodes in the graph:\n", listOfDegrees)

Here is a list of the degrees of the nodes in the graph:
 [21, 18, 34, 34, 31, 32, 31, 45, 44, 48, 42, 45, 24, 38, 35, 39, 43, 39, 28, 21, 25, 16, 17, 26, 42, 37, 25, 53, 17, 24, 14, 26, 20, 39, 34, 32, 29, 57, 44, 38, 31, 21, 47, 38, 23, 22, 21, 23, 39, 8, 18, 17, 21, 4, 43, 33, 29, 31, 19, 23, 34, 43, 8, 20, 16, 11, 16, 20, 12, 32, 15, 34, 23, 20, 45, 43, 14, 24, 13, 22, 23, 28, 49, 24, 25, 22, 12, 21, 40, 17, 29, 23, 19, 38, 38, 16, 33, 11, 3, 5, 35, 27, 15, 13, 23, 9, 4, 23, 18, 23, 22, 2, 7, 31, 17, 27, 5, 34, 13, 21, 5, 18, 18, 14, 15, 23, 22, 13, 3, 12, 23, 10, 6, 12, 2, 4, 3, 4, 10, 6, 6, 3, 3, 10, 2, 1, 6, 2, 1, 1]


In [ ]:
#Now let us look at the maximum degree of the nodes. We go through the list of the nodes' degree and we update 
#the value of the maximum degree if the degree from the list is bigger than the maximum degree.
#For the average degree, we go through the list of degrees and add each value in it together. At the end, we 
#calculate 2* the sum of the degrees divided by the total number of nodes.

In [ ]:
maximumDegree = 0
averageDegree = 0

for i in listOfDegrees:
    averageDegree = averageDegree + i
    
    if maximumDegree < i:
        maximumDegree = i

averageDegree = 2*averageDegree / numberOfNodes

print("Maximum degree is:", maximumDegree)
print("Average degree is:", averageDegree)

Maximum degree is: 57
Average degree is: 45.14666666666667


In [ ]:
#Question (c)

In [ ]:
#We initialize an undirected graph, called graphPartial.

In [ ]:
graphPartial = snap.TUNGraph.New()

In [ ]:
#We create a list and define the number of partial nodes as being 6. While the list does not contain 6 nodes, 
#random picked nodes from the previous graph are added to the list if they are not already inside.
#The last for-loop adds each node from the list of partial nodes to the partial graph.

In [ ]:
listOfPartialNodes = []
numberOfPartialNodes = 6

while len(listOfPartialNodes) < numberOfPartialNodes:
    NId = graph.GetRndNId()
    if NId not in listOfPartialNodes:
        listOfPartialNodes.append(NId)

for node in listOfPartialNodes:
    graphPartial.AddNode(node)

print("The nodes chosen are", listOfPartialNodes)

The nodes chosen are [483, 620, 394, 671, 576, 599]


In [ ]:
#We go through the dataset file and add an edge to the partial graph for every two nodes which were written in the 
#same line (separated by a whitespace) on the file.

In [ ]:
with open(filename) as f:
    for line in f:
        x = line.split()
        a = int(x[0])
        b = int(x[1])
        
        if a in listOfPartialNodes and b in listOfPartialNodes:
            graphPartial.AddEdge(a, b)

In [ ]:
#As we done it before, we count the number of nodes in the partial graph.

In [ ]:
numberOfPartialNodes = 0
for i in graphPartial.Nodes():
    numberOfPartialNodes = numberOfPartialNodes + 1
print("There are", numberOfPartialNodes, "nodes in the partial graph.")

There are 6 nodes in the partial graph.


In [ ]:
#As we done it before, we count the number of edges in the partial graph.

In [ ]:
numberOfPartialEdges = 0
for i in graphPartial.Edges():
    numberOfPartialEdges = numberOfPartialEdges + 1
print("There are", numberOfPartialEdges, "edges in the partial graph.")

There are 3 edges in the partial graph.


In [ ]:
#We create a 6x6 matrix with 0 at every entry. The number 6 is the number of node for the partial graph,
#it will change when desired the number of nodes changes. Then at every entry, it checks if there is an edge between
#every two nodes. If there is an edge, then at that entry there will be a 1. Otherwise, at that entry of the matrix
#there will be a 0.

In [ ]:
adjMatrix = np.empty((numberOfPartialNodes,numberOfPartialNodes))

row = 0
for a in listOfPartialNodes:
    column = 0
    
    for b in listOfPartialNodes:
        if graphPartial.IsEdge(a, b) == True:
            adjMatrix[row][column] = 1
        else:
            adjMatrix[row][column] = 0
            
        column = column + 1
        
    row = row + 1

print("The adjacency matrix of the partial graph with the following nodes", listOfPartialNodes, "is:\n", adjMatrix)

The adjacency matrix of the partial graph with the following nodes [348, 663, 606, 436, 659, 595] is:
 [[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]]


In [ ]:
#Small notice: since i am picking nodes at random, there can be some nodes which have no edge in between them. This
#leads to a zero adjacency matrix.

In [ ]:
#The adjacency matrix tells a lot about a graph. First, we can see if the matrix is symmetric or asymmetric.
#If it is asymmetric, we know that the graph is a directed graph. However, if it symmetric, we know that the graph is
#undirected graph.
#Now the entries tell us if there is an edge between the node at i column and the node at j row. The number 1 at the
#entry means there is an edge between the two nodes. The number 0 at the entry means there is an edge between the two
#nodes. So with only the adjacency matrix, we should be able to reconstruct the graph (or an equivalent one). 

In [ ]:
#Here are the other dataset files. However for this assignment, we haven't done anything with it.

In [ ]:
f = open("/Users/carolina/Documents/Semester_9/Analysis_of_Complex_Network/Group4/Facebook-Ego/414.egofeat", "r")
print(f.read())

0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0



In [ ]:
f = open("/Users/carolina/Documents/Semester_9/Analysis_of_Complex_Network/Group4/Facebook-Ego/414.feat", "r")
print(f.read())

573 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
574 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
575 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
576 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
577 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 1 

In [ ]:
f = open("/Users/carolina/Documents/Semester_9/Analysis_of_Complex_Network/Group4/Facebook-Ego/414.featnames", "r")
print(f.read())

0 birthday;anonymized feature 208
1 birthday;anonymized feature 0
2 birthday;anonymized feature 1
3 birthday;anonymized feature 209
4 birthday;anonymized feature 2
5 birthday;anonymized feature 3
6 birthday;anonymized feature 211
7 education;concentration;id;anonymized feature 14
8 education;concentration;id;anonymized feature 15
9 education;concentration;id;anonymized feature 311
10 education;concentration;id;anonymized feature 215
11 education;concentration;id;anonymized feature 216
12 education;concentration;id;anonymized feature 217
13 education;concentration;id;anonymized feature 312
14 education;degree;id;anonymized feature 220
15 education;degree;id;anonymized feature 313
16 education;degree;id;anonymized feature 22
17 education;degree;id;anonymized feature 221
18 education;degree;id;anonymized feature 23
19 education;degree;id;anonymized feature 222
20 education;degree;id;anonymized feature 223
21 education;school;id;anonymized feature 314
22 education;school;id;anonymized feat